apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: tcs-service
  description: TCS microservice

  annotations:
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: production
  owner: group:default/tcs-teams

  dependsOn:
    - resource:default/tcs-db

  providesApis:
    - tcs-api
